{{- if .Values.ingress.well_known.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: continuwuity-nginx-static-json
data:
{{- if .Values.config.allow_federation }}
  server: |-
    {{- $port := .Values.config.federation_port | toString -}}
    {{- printf "{\"m.server\":\"https://%s:%s\"}" .Values.config.server_name $port | nindent 4 }}
{{- end }}
  client: |-
    {
      "m.homeserver": {
        "base_url": "https://{{ .Values.config.server_name }}"
      },
      "m.identity_server": {
        "base_url": "https://{{ .Values.config.identity_server }}"
      }
    }
{{- end }}