{{- if .Values.ingress.well_known.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: continuwuity-nginx-static-json
data:
{{- if .Values.config.allow_federation }}
server: |-
    {{- $port := .Values.config.federation_port | toString -}}
    {{- printf "{\"m.server\":{\"https://%s:%s\"}}" .Values.config.server_name $port | nindent 4 }}
{{- end }}
  client: |-
    {
      "m.homeserver": {
    {{- printf "{\"base_url\":{\"https://%s\"}}" .Values.config.server_name | nindent 4 }}
      },
      "m.identity_server": {
    {{- printf "{\"base_url\":{\"https://%s\"}}" .Values.config.identity_server | nindent 4 }}
      }
    }
{{- end }}