{{- if .Values.ingress.well_known.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: continuwuity-nginx-static-json
data:
{{- if .Values.config.allow_federation }}
  server: |-
    {{- $server := dict "m.server" (printf "https://%s:%s" .Values.config.server_name .Values.config.federation_port) -}}
    {{- $server | toYaml | nindent 4 }}
{{- end }}
  client: |-
    {{- $client := dict "m.homeserver" (dict "base_url" .Values.config.server_name) "m.identity_server" (dict "base_url" "https://vector.im") -}}
    {{- $client | toYaml | nindent 4 }}
{{- end }}