{{- if .Values.ingress.well_known.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: continuwuity-static-nginx-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: continuwuity-static-nginx-server
  template:
    metadata:
      labels:
        app: continuwuity-static-nginx-server
    spec:
      initContainers:
      - name: fix-permissions
        image: busybox:latest
        command: ["sh","-c","mkdir -p /usr/share/nginx/html /etc/nginx && chown -R 101:101 /usr/share/nginx/html && chwon -R 101:101 /etc/nginx"]
        volumeMounts:
        - name: json-volume
          mountPath: /usr/share/nginx/html/
        - name: config-volume
          mountPath: /etc/nginx/
          subPath: nginx.conf
      containers:
      - name: nginx
        image: nginx:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        volumeMounts:
        - name: json-volume
          mountPath: /usr/share/nginx/html/
        - name: config-volume
          mountPath: /etc/nginx/
          subPath: nginx.conf
      securityContext:
        fsGroup: 101
      volumes:
      - name: json-volume
        configMap:
          name: continuwuity-nginx-static-json
      - name: config-volume
        configMap:
          name: continuwuity-nginx-static-config
{{- end }}