{{- if .Values.ingress.well_known.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: continuwuity-static-nginx-service
spec:
  {{- if .Values.service.clusterIP }}
  clusterIP: {{ .Values.service.clusterIP | quote }}
  {{- end }}
  {{- if .Values.service.externalIPs }}
  externalIPs:
    {{- toYaml .Values.service.externalIPs | nindent 4 }}
  {{- end }}
  {{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP | quote }}
  {{- end }}
  {{- if .Values.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
    {{- toYaml .Values.service.loadBalancerSourceRanges | nindent 4 }}
  {{- end }}
  ports:
  - protocol: TCP
    port: {{ .Values.ingress.well_known.port }}
    targetPort: http
  selector:
    app: continuwuity-static-nginx-server
  type: {{ .Values.service.type }}
{{- end }}